In [5]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv('vendas_tech.csv', encoding= 'latin1', low_memory=False)
display(df_vendas)
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")
display(df_gerentes) 

def load_data(arquivo):
    if arquivo.endswith('.csv'):
        return pd.read_csv(arquivo, encoding='latin1', low_memory=False)
    elif arquivo.endswith('.xlsx'):
        return pd.read_excel(arquivo)
    else:
        raise ValueError("Formato de arquivo não suportado. Use .csv ou .xlsx")
    
load_data('vendas_tech.csv')
load_data('gerentes_lojas.xlsx')

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,SÃ£o Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,SÃ£o Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [6]:
# display(df_vendas["Loja"])
# display(df_vendas[["Loja", "Cliente"]])

df_analise = df_vendas.drop(columns=["Data_Base"])
display(df_analise)

# Dropna = Analise de dados, remove linhas com valores nulos (no mínimo 1 valor nulo)
# df_analise = df_analise.dropna()
# display(df_analise)

# Fillna = Analise de dados, substitui valores nulos por um valor especificado
df_analise["Loja"] = df_analise["Loja"].fillna('Online').str.strip().str.title()

df_analise["Data"] = pd.to_datetime(df_analise["Data"], format='%d/%m/%Y')
display(df_analise)

df_analise = df_analise.drop_duplicates(subset=["ID_Pedido", "Loja"], keep='first')

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,SÃ£o Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,SÃ£o Paulo,Notebook HP,3200.0,2,Cliente_3274

ValueError: time data "2023-06-08" doesn't match format "%d/%m/%Y", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [11]:
df_vendas["Faturamento"] = df_vendas["Qtd"] * df_vendas["Preco_Unitario"]

df_analise["Forma_de_Venda"] = np.where(df_analise["Loja"] == "Online", "Online", "Presencial")

display(df_analise["Loja"].unique(), enconding='latin1', low_memory=False)

dic_regioes = {
    "São Paulo": "Sudeste",
    "Rio de Janeiro": "Sudeste",
    "Belo Horizonte": "Sudeste",
    "Online": "Online",
    "Salvador": "Nordeste",
    "Recife": "Nordeste",
    "Curitiba": "Sul",
    "Porto Alegre": "Sul",
}

def definir_regiao(loja):
    return dic_regioes.get(loja, "Outros")

df_analise["Regiao"] = df_analise["Loja"].map(definir_regiao)
display(df_analise.isna().sum())

array(['Porto Alegre', 'Curitiba', 'Salvador', 'Rio De Janeiro', 'Online',
       'Sã£O Paulo', 'Belo Horizonte', 'Recife'], dtype=object)

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
Forma_de_Venda    0
Regiao            0
dtype: int64

In [ ]:
df_analise = df_analise.sort_values(by="Data", ascending=False).reset_index(drop=True)
df_analise = df_analise.reset_index(drop=True)

id_pedido = 4
loja = df_analise.loc[3, "Loja"]
produto = df_analise.loc[3, "Produto"]
cliente = df_analise.loc[3, "Cliente"]
print(f"ID do Pedido: {id_pedido}, Loja: {loja}, Produto: {produto}, Cliente: {cliente}")

id_pedido = 4
loja = df_analise.iloc[3, 2]
cliente = df_analise.iloc[3, 3]
produto = df_analise.iloc[3, 4]
print(f"ID do Pedido: {id_pedido}, Loja: {loja}, Produto: {produto}, Cliente: {cliente}")

df_id_pedido_4 = df_analise[df_analise["ID_Pedido"] == 4]

df_vendas_sp = df_analise[df_analise["Loja"] == "São Paulo"]
df_vendas_sp.to_csv("vendas_sao_paulo.csv", index=False, encoding='latin1')

df_vendas_2024 = df_analise[df_analise["Data"].dt.year == 2024]
df_vendas_2024.to_csv("vendas_2024.csv", index=False, encoding='latin1')

df_vendas_HDMI_sul = df_analise[(df_analise["Produto"].str.contains("HDMI")) & (df_analise["Regiao"] == "Sul")]
df_vendas_HDMI_sul.to_csv("vendas_hdmi_sul.csv", index=False, encoding='latin1')

In [ ]:

analise_lojas = df_analise.groupby(["Loja", "Faturamento"]).groupby("Loja").sum()
analise_lojas = analise_lojas.sort_values(by="Faturamento", ascending=False)
analise_lojas = analise_lojas.reset_index()
analise_lojas["Faturamento"] = analise_lojas["Faturamento"].map("R${:,.2f}".format)

df_vendas_online = df_analise[df_analise["Loja"] == "Online"]
df_vendas_presencial = df_analise[df_analise["Loja"] == "Presencial"]
analise_produtos_online = df_vendas_online[["Produto", "Faturamento"]].groupby("Produto").sum().sort_values(by="Qtd", ascending=False)
analise_produtos_presencial = df_vendas_presencial[["Produto", "Faturamento"]].groupby("Produto").sum().sort_values(by="Qtd", ascending=False)
analise_produtos_online = analise_produtos_online.rename(columns={"Qtd": "Vendas Totais Online"})
analise_produtos_presencial = analise_produtos_presencial.rename(columns={"Qtd": "Vendas Totais Presencial"})

display(analise_lojas)

In [ ]:
analise_produtos_em_lojas = df_analise[["Loja", "Produto", "Qtd"]].groupby(["Loja", "Produto"]).sum().sort_values(by="Qtd", ascending=False)
analise_produtos_em_lojas.to_csv("analise_produtos_em_lojas.csv", index=True, encoding='latin1')

with pd.option_context('display.max_rows', None):
    display(analise_produtos_em_lojas)

analise_lojas_em_produtos = df_analise[["Produto", "Loja", "Qtd"]].groupby(["Produto", "Loja"]).sum().sort_values(by="Qtd", ascending=False)

In [ ]:
df_meta = df_analise[df_analise["Data"].dt.year == 2023 & (df_analise["Data"].dt.month == 1)]

df_meta = df_meta[["Loja", "Faturamento"]].groupby("Loja", as_index=False).sum()

df_meta = df_meta.merge(df_gerentes, on="Loja", how="left")
df_meta["Bateu Meta"] = df_meta["Faturamento"] >= df_meta["Meta_Mensal"]
df_meta["Bateu Meta"] = df_meta["Bateu Meta"].map({True: "Sim", False: "Não"})